#!/bin/sh
# Xcode Cloud runs this automatically after cloning, before the build.
# The Xcode project is generated by XcodeGen (see project.yml) and is
# gitignored, so it must be regenerated in the CI checkout.
set -e

echo "Installing XcodeGen..."
brew install xcodegen

echo "Generating Marginal.xcodeproj from project.yml..."
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "Done. Project layout:"
ls -d *.xcodeproj
